### ISSUE TITLE
tpie::parallel() hangs on std::thread::join() when pipeline is destructed because of exception

### ISSUE THREAD

**Issue by freekvw** [thomasmoelhave/tpie#215]
We have a pipeline looking like: `p = doSomething() | tpie::parallel(...) | ...;`, where `doSomething()` throws an exception. This causes `p` to be destructed (because out of scope), which triggers `tpie::pipelining::parallel_bits::before::~before()` to call `m_worker.join()`.  The threads are however not told to quit and are waiting for condition variable `the_job_manager->m_has_data` in `job_manager::worker()`.
I haven't looked into it further, it took some time to find out that an exception was thrown as it wasn't in the stack trace, so I thought it would be good to note and hope the info above is enough to reproduce and/or fix this, otherwise let me know.

**Comment by Tyilo** [comment]
This seems to have been fixed by 42e5ffb31c853b47a39ba8105648b848001b7dbc, could you test it again?

See 02a0244d30b1baaf303ddd22208a8c362eae5fde for the test, which would hang before, but doesn't anymore.

**Comment by freekvw** [comment]
I reconstructed the problem and it still fails as described above.  I'll see if I can make a/your testcase fail.

**Comment by Tyilo** [comment]
Yeah, I didn't actual fix it sorry.

**Comment by freekvw** [comment]
Ah ok, I now see you comment also disappeared :-)

**Comment by Tyilo** [comment]
OK, now it should have been fixed, could you confirm if it works?

**Comment by freekvw** [comment]
Works now :-) Thanks!
